### ISSUE TITLE
Unit InstanceID for Dire Maul indicates Unit is in instance when they are not

### ISSUE THREAD

**Issue by Jakobud** [Nevcairiel/HereBeDragons#10]
This might be a bug or limitation of the WoW API but I'm not sure. Also this is regarding WoW Classic:

I've noticed that when trying to determine if a unit that is in your party/raid is in an instance or not, that the game can't tell the difference between being actually inside the Dire Maul instance and being outside the instance in the courtyard area. In both cases, the WoW API returns an instanceID of `429`.

It seems that when you approach Dire Maul the game considers you inside the instance and returns your instance ID as such.

Also if you notice, when a unit is approaching Dire Maul they disappear from the world map when they get close to Dire Maul but have still not zoned in. I assume this is related to the issue.

Anyways, have you been able to figure out a work-around to this? I'm trying to determine when a unit is specifically zoned-into Dire Maul but I think there might just not be a way.

**Comment by Nevcairiel** [comment]
HBD just mirrors the data the game offers. You can augment it with IsInInstance() or other such functions if the map ID alone is not enough.
