### ISSUE TITLE
Opening adventure guide in combat fails due to taint

### ISSUE THREAD

**Issue by ExAstrisScientia** [Nevcairiel/HereBeDragons#11]
A minor issue, after months of just living with it I finally managed to isolate the symptoms a bit more properly:

If HBD is loaded, either as standalone or as an embedded library in another addon (e.g. TomTom, WorldQuestTracker, Gathermate, Rarescanner,...), opening the adventure guide by clicking on the dungeon symbol of the world map in combat fails with an "Interface action failed because of an addon" message in chat. When combat ends, normal behaviour is restored. No lua errors are thrown, but the taint log has some entries: 
[taintlog-HBD-idle.log](https://github.com/Nevcairiel/HereBeDragons/files/5426218/taintlog-HBD-idle.log)

This taint log is created by _\reload_-ing, opening the quest log/map by pressing _l_, then clicking on a dungeon portal in a setup with standalone HBD as the only addon that is loaded, all others deactivated. I've also created a log by repeating this entire procedure while in combat, the output is identical (For some addons that load HBD as an embedded library, like e.g. SilverDragon, the output can be different between in-combat and out-of-combat reloading and opening the adventure guide, but as HBD on its own does not show differences, I assume these are differences due to the addon in question, not HBD). In the OOC case, the adventure guide opens normally, in combat it fails, despite the identical taint logs.

The impact is of course very limited, the only real consequence is that I can't check the loot table while in combat (if it is not already open, that is). So my raid leader might not even regard this as an issue, actually...
Nevertheless, I assume this is unintended behaviour, so I thought I'd mention it.

This affects (at least) major release 2 with minor releases 5,7, and 14. Minor releases 5 and 7 are embedded in WorldQuestTracker and NPCScan, release 14 is the current CurseForge version and embedded in a variety of addons. Loading any addon that embeds HBD as the only active addon yields the same problem, the taint logs are just longer and contain additional taints originating from these addons' own code, as well.

**Comment by Nevcairiel** [comment]
There is really nothing that can be done about this. Any addon that would interact with the World Map through the official Blizzard-provided API to add additional content to the map, as HereBeDragons-Pins does, will cause the exact same taint.

In fact, that is the only external code it accesses in any manner that might taint - it registers its own data provider with the map, through the interface the new Map API introduced in WoW 8.0 provides. Incidentally, around the same timeframe Blizzard locked down showing/hiding of UI Panel from insecure code, hence the problem occurs.

**Comment by ExAstrisScientia** [comment]
Thanks for the explanation (and indeed thank you for writing an addon that I've only found out to be a backbone of my interface when investigating this!), I'll just have to check loot tables before the fight, then ;)
