### ISSUE TITLE
Translate Zereth Mortis to Shadowlands

### ISSUE THREAD

**Issue by p3lim** [Nevcairiel/HereBeDragons#15]
E.g. show pins on mapID 1970 on its parent map; 1550.

Might be a big ask considering the ZM representation on the Shadowlands map is tiny, but it's up to you.

**Comment by Nevcairiel** [comment]
Translations are extracted from Blizzard data, not manually crafted. If they don't provide it, I'm not that inclined to add it. That said I haven't checked what their map APIs do, but I don't think anything shows on the SL "continent" map?

**Comment by p3lim** [comment]
> but I don't think anything shows on the SL "continent" map?

You mean from ZM? No. From the other 5 zones (Maldraxxus, Revendreth, Ardenweald, Bastion, The Maw), yes.
