### ISSUE TITLE
HBD:GetZoneCoordinatesFromWorld() wrong calculation in v2.14 for Kalimdor

### ISSUE THREAD

**Issue by Dathwada** [Nevcairiel/HereBeDragons#18]
[We](https://github.com/zarillion/handynotes-plugins) have the problem that the function `HBD:GetZoneCoordinatesFromWorld()` calculates the wrong coordinates if the parent map is Kalimdor (UiMapID: 12) in HBD version 2.14.

The child maps we have this problems are:
* Durotar (UiMapID: 1)
* Felwood (UiMapID: 77)
* Moonglade (UiMapID: 80)

I downgraded HBD in HandyNotes back to version 2.13 and now it calculates the correct coordinates we need for our nodes on the parent map.

You can reproduce this behavior yourself with this command:
```
/run local HBD = LibStub('HereBeDragons-2.0'); local x, y = HandyNotes:getXY(56001200); local wx, wy = HBD:GetWorldCoordinatesFromZone(x, y, 1); local px, py = HBD:GetZoneCoordinatesFromWorld(wx, wy, 12); print(px, py);
```
OUTPUT:
```
v2.13: 0.59756032124199 0.44527033917726
v2.14: nil nil (allowOutOfBounds = false)
v2.14: -2.7565260731609 -0.84089392765724 (allowOutOfBounds = true)
```
Version 2.13 calculates the expected coordinates for the parent map.

**Comment by Nevcairiel** [comment]
That should hopefully be fixed, the 11.0.2 data was mistakenly already loaded now.

**Comment by Dathwada** [comment]
Wow, that was quick. But unfortunately this is still happening in version 2.14.1.

**Comment by Nevcairiel** [comment]
Turns out there were two separate issues stemming from 11.0 updates, but it should be better now.

**Comment by Dathwada** [comment]
I can confirm that this is now fixed. Thank you very much.
