### ISSUE TITLE
"Attempt to call method 'GetPlayerWorldPosition'"

### ISSUE THREAD

**Issue by ghost** [Nevcairiel/HereBeDragons#2]
...om\libs\HereBeDragons-1.0-17\HereBeDragons-Pins-1.0-11.lua:158: attempt to call method 'GetPlayerWorldPosition' (a nil value)
...om\libs\HereBeDragons-1.0-17\HereBeDragons-Pins-1.0-11.lua:158: in function <...om\libs\HereBeDragons-1.0\HereBeDragons-Pins-1.0.lua:156>
...om\libs\HereBeDragons-1.0-17\HereBeDragons-Pins-1.0-11.lua:344: in function <...om\libs\HereBeDragons-1.0\HereBeDragons-Pins-1.0.lua:335>

Locals:
force = nil
(_temporary) = nil
(_temporary) = <table> {
 mapData = <table> {
 }
 callbacks = <table> {
 }
 RegisterCallback = <function> defined @ElvUI\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:116
 transforms = <table> {
 }
 microDungeons = <table> {
 }
 UnregisterCallback = <function> defined @ElvUI\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:179
 mapToID = <table> {
 }
 eventFrame = <unnamed> {
 }
 continentZoneMap = <table> {
 }
}
(*temporary) = "attempt to call method 'GetPlayerWorldPosition' (a nil value)"
HBD = <table> {
 mapData = <table> {
 }
 callbacks = <table> {
 }
 RegisterCallback = <function> defined @ElvUI\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:116
 transforms = <table> {
 }
 microDungeons = <table> {
 }
 UnregisterCallback = <function> defined @ElvUI\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:179
 mapToID = <table> {
 }
 eventFrame = <unnamed> {
 }
 continentZoneMap = <table> {
 }
}
pins = <table> {
 minimapPins = <table> {
 }
 SetMinimapObject = <function> defined @TomTom\libs\HereBeDragons-1.0\HereBeDragons-Pins-1.0.lua:474
 RemoveMinimapIcon = <function> defined @TomTom\libs\HereBeDragons-1.0\HereBeDragons-Pins-1.0.lua:448
 IsMinimapIconOnEdge = <function> defined @TomTom\libs\HereBeDragons-1.0\HereBeDragons-Pins-1.0.lua:437
 Minimap = Minimap {
 }
 RemoveAllWorldMapIcons = <function> defined @TomTom\libs\HereBeDragons-1.0\HereBeDragons-Pins-1.0.lua:587
 AddMinimapIconMF = <function> defined @TomTom\libs\HereBeDragons-1.0\HereBeDragons-Pins-1.0.lua:413
 worldmapPins = <table> {
 }
 RemoveAllMinimapIcons = <function> defined @TomTom\libs\HereBeDragons-1.0\HereBeDragons-Pins-1.0.lua:461
 updateFrame = <unnamed> {
 }
 AddMinimapIconWorld = <function> defined @TomTom\libs\HereBeDragons-1.0\HereBeDragons-Pins-1.0.lua:374
 RemoveWorldMapIcon = <function> defined @TomTom\libs\HereBeDragons-1.0\HereBeDragons-Pins-1.0.lua:575
 GetVectorToIcon = <function> defined @TomTom\libs\HereBeDragons-1.0\HereBeDragons-Pins-1.0.lua:600
 AddWorldMapIconMF = <function> defined @TomTom\libs\HereBeDragons-1.0\HereBeDragons-Pins-1.0.lua:532
 AddWorldMapIconWorld = <function> defined @TomTom\libs\HereBeDragons-1.0\HereBeDragons-Pins-1.0.lua:489
 worldmapPinRegistry = <table> {
 }
 activeMinimapPins = <table> {
 }
 minimapPinRegistry = <table> {
 }
}
lastZoom = nil
rotateMinimap = false
GetPlayerFacing = <function> defined =[C]:-1
lastFacing = nil
minimapScale = nil
lastXY = nil
lastYY = nil
minimapShape = nil
minimap_shapes = <table> {
 SQUARE = <table> {
 }
 SIDE-RIGHT = <table> {
 }
 SIDE-TOP = <table> {
 }
 CORNER-TOPRIGHT = <table> {
 }
 SIDE-BOTTOM = <table> {
 }
 TRICORNER-TOPRIGHT = <table> {
 }
 CORNER-BOTTOMRIGHT = <table> {
 }
 TRICORNER-BOTTOMLEFT = <table> {
 }
 TRICORNER-BOTTOMRIGHT = <table> {
 }
 TRICORNER-TOPLEFT = <table> {
 }
 SIDE-LEFT = <table> {
 }
 CORNER-BOTTOMLEFT = <table> {
 }
 CORNER-TOPLEFT = <table> {
 }
}
mapRadius = nil
minimap_size = <table> {
 outdoor = <table> {
 }
 indoor = <table> {
 }
}
indoors = "outdoor"
minimapWidth = nil
minimapHeight = nil
mapSin = nil
sin = <function> defined =[C]:-1
mapCos = nil
cos = <function> defined =[C]:-1
pairs = <function> defined =[C]:-1
minimapPins = <table> {
}
activeMinimapPins = <table> {
}
drawMinimapPin = <function> defined @TomTom\libs\HereBeDragons-1.0\HereBeDragons-Pins-1.0.lua:104
minimapPinCount = 0

**Comment by Nevcairiel** [comment]
This is an outdated version of the library. Please inform the author  this is included in to update it.
