### ISSUE TITLE
Request: Add More Callbacks

### ISSUE THREAD

**Issue by MysticalOS** [Nevcairiel/HereBeDragons#7]
Specifically, I was hoping you could add callbacks for AddWorldMapIconMap and RemoveWorldMapIcon (with all the args of course)

This would allow other mods, such as DBM Hud to show icons when you do and it's best to be in HBD because then it doesn't need to be in questie, handynotes, gathermate, etc when I am hoping to work on integrations for all 3, which all base their Pins off HBD.

**Comment by Nevcairiel** [comment]
I'm not sure what a Pin Added or Pin Removed message would actually be good for.  The addon provides a pin frame, not a texture, so ultimately there is only one frame, which means you would have to steal the one thats given to HBDP, which personally I do not like as a concept, as it interfers with the baseline functionality of HBDP - why should I add a function to be able to basically break HBDP?

Most HUDs I've ever seen are based on minimap logic, in which case there is actually an API in HBDP to offer an alternate minimap frame, but of course the same limitations apply, as a single pin frame can only be in a single location.
