### ISSUE TITLE
HereBeDragons-Pins-2.0 causes taint

### ISSUE THREAD

**Issue by syndenbock** [Nevcairiel/HereBeDragons#8]
I figured out some addons caused taint with the QuestTracker, causing quests in the QuestTracker not being able to be clicked while in combat.
I traced the problem back to HereBeDragons-Pins-2.0, which seems to cause the taint.

For example when having TomTom enabled, I can only open and close a quest once by clicking it on the tracker. Afterwards I get a taint message and cannot open the quest anymore while in combat.
If I comment out HereBeDragons-Pins-2.0 and TomTom_Waypoints (because it uses HBDP) from TomToms TOC file, the issue goes away.
I could not figure out which code causes this taint though.

I have some other addons which are also using HereBeDragons-Pins-2.0 and all of them have the same taint issue when enabled:
Handynotes, WorldQuestTracker, GatherMate2, Silverdragon

**Comment by Nevcairiel** [comment]
HereBeDragons-Pins does nothing tainting other then use the official API provided by Blizzard to add pins to the World Map. If this taints the Quest Tracker, then complain to Blizzard, since there is no choice but to use this API really, like many other addons also do.

**Comment by Nevcairiel** [comment]
For the record, I can click quests in my quest tracker while in combat just fine with all sorts of addons enabled.

**Comment by syndenbock** [comment]
I did some more testing with only having TomTom enabled and figured out that this only happens for world quests.
I have a normal quest and a world quest in the tracker. I can click the normal quest just fine, but the world quest can only be clicked 1-2 times, then I get a taint message. I assume this has to do something with the reward tooltip, as normal quests don't have rewards displayed in the tracker.

I can also understand there may no way to fix this, as Blizzard aren't particularily good in creating their API.

**Comment by Nevcairiel** [comment]
I'll re-try with World Quests a bit later. Maybe I can make a proper bug report to Blizzard, but I'm pretty certain I already know why its happening, and fixing that properly may be hard.

But, if you use a map addon, like my Mapster, it may be possible to work around it, ie. maybe with something like this that i'm currently testing:
https://github.com/Nevcairiel/Mapster/commit/3e967522f400910349fe83053bd1d03cc7bd8a9f

**Comment by syndenbock** [comment]
That sounds awesome, thanks for your work!
